import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import ThemesProviders from "./providers/ThemesProviders";
import Navigation from "@/components/Navigation";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className={geistSans.className}>
      <body>
        <ThemesProviders>
          <Navigation />
          {children}
        </ThemesProviders>
      </body>
    </html>
  );
}
